# Generated by Django 6.0.1 on 2026-02-15 18:43

from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_add_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.users.models.avatar_upload_path
            ),
        ),
    ]
