# Generated by Django 6.0.1 on 2026-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "draft"), ("published", "published")], max_length=10
            ),
        ),
    ]
